name: 4× Daily YouTube Metrics Update

on:
  workflow_dispatch:
  schedule:
    # Runs at 06:00, and 18:00 UTC each day
    - cron: '0 6,18 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run metrics updater
        env:
          SUPABASE_URL:        ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          YT_API_KEYS:         ${{ secrets.YT_API_KEYS }}
        run: node update.js


